import type { CEFRLevel } from "@/lib/vocab/types";

export interface BatchSentence {
  id: string;
  de: string;
  en: string;
  level: CEFRLevel;
  category: string;
}

export const BATCH_SENTENCES: BatchSentence[] = [
  // ── TRANSPORT (10) ──
  {
    id: "transport-001",
    de: "Der Bus fährt alle zwanzig Minuten.",
    en: "The bus runs every twenty minutes.",
    level: "A2",
    category: "transport",
  },
  {
    id: "transport-002",
    de: "Der Zug hat zwanzig Minuten Verspätung.",
    en: "The train is twenty minutes late.",
    level: "B1",
    category: "transport",
  },
  {
    id: "transport-003",
    de: "Ich nehme jeden Tag die U-Bahn.",
    en: "I take the subway every day.",
    level: "A2",
    category: "transport",
  },
  {
    id: "transport-004",
    de: "Das Flugzeug landet in einer Stunde.",
    en: "The plane lands in one hour.",
    level: "A2",
    category: "transport",
  },
  {
    id: "transport-005",
    de: "Sie fährt mit dem Fahrrad zur Arbeit.",
    en: "She cycles to work.",
    level: "A2",
    category: "transport",
  },
  {
    id: "transport-006",
    de: "Der Stau auf der Autobahn ist lang.",
    en: "The traffic jam on the motorway is long.",
    level: "B1",
    category: "transport",
  },
  {
    id: "transport-007",
    de: "Ich habe meinen Zug verpasst.",
    en: "I missed my train.",
    level: "B1",
    category: "transport",
  },
  {
    id: "transport-008",
    de: "Das Ticket gilt für alle Zonen.",
    en: "The ticket is valid for all zones.",
    level: "B1",
    category: "transport",
  },
  {
    id: "transport-009",
    de: "Der Fahrer kennt die Stadt sehr gut.",
    en: "The driver knows the city very well.",
    level: "A2",
    category: "transport",
  },
  {
    id: "transport-010",
    de: "Wir warten seit einer Stunde auf den Bus.",
    en: "We have been waiting for the bus for an hour.",
    level: "B1",
    category: "transport",
  },

  // ── FOOD & DRINK (10) ──
  {
    id: "food-001",
    de: "Ich trinke morgens immer Kaffee.",
    en: "I always drink coffee in the morning.",
    level: "A1",
    category: "food",
  },
  {
    id: "food-002",
    de: "Sie kocht heute Abend Spaghetti.",
    en: "She is cooking spaghetti tonight.",
    level: "A1",
    category: "food",
  },
  {
    id: "food-003",
    de: "Das Brot ist heute frisch gebacken.",
    en: "The bread is freshly baked today.",
    level: "A2",
    category: "food",
  },
  {
    id: "food-004",
    de: "Er bestellt immer die Tagesempfehlung.",
    en: "He always orders the daily special.",
    level: "B1",
    category: "food",
  },
  {
    id: "food-005",
    de: "Die Suppe ist zu heiß zum Trinken.",
    en: "The soup is too hot to drink.",
    level: "A2",
    category: "food",
  },
  {
    id: "food-006",
    de: "Wir essen jeden Sonntag gemeinsam.",
    en: "We eat together every Sunday.",
    level: "A2",
    category: "food",
  },
  {
    id: "food-007",
    de: "Das Restaurant hat heute geschlossen.",
    en: "The restaurant is closed today.",
    level: "A2",
    category: "food",
  },
  {
    id: "food-008",
    de: "Sie trinkt ihren Kaffee immer schwarz.",
    en: "She always drinks her coffee black.",
    level: "B1",
    category: "food",
  },
  {
    id: "food-009",
    de: "Der Kuchen riecht wunderbar.",
    en: "The cake smells wonderful.",
    level: "A2",
    category: "food",
  },
  {
    id: "food-010",
    de: "Ich habe großen Hunger nach der Arbeit.",
    en: "I am very hungry after work.",
    level: "B1",
    category: "food",
  },

  // ── DAILY LIFE (10) ──
  {
    id: "daily-001",
    de: "Ich stehe jeden Morgen um sieben auf.",
    en: "I get up at seven every morning.",
    level: "A1",
    category: "daily_life",
  },
  {
    id: "daily-002",
    de: "Sie kauft jeden Samstag auf dem Markt ein.",
    en: "She shops at the market every Saturday.",
    level: "A2",
    category: "daily_life",
  },
  {
    id: "daily-003",
    de: "Er liest abends zur Entspannung.",
    en: "He reads in the evenings to relax.",
    level: "B1",
    category: "daily_life",
  },
  {
    id: "daily-004",
    de: "Die Kinder spielen im Garten.",
    en: "The children are playing in the garden.",
    level: "A1",
    category: "daily_life",
  },
  {
    id: "daily-005",
    de: "Ich habe heute meine Hausaufgaben gemacht.",
    en: "I did my homework today.",
    level: "A2",
    category: "daily_life",
  },
  {
    id: "daily-006",
    de: "Sie ruft ihre Mutter jeden Sonntag an.",
    en: "She calls her mother every Sunday.",
    level: "A2",
    category: "daily_life",
  },
  {
    id: "daily-007",
    de: "Das Wetter ist heute sehr schön.",
    en: "The weather is very nice today.",
    level: "A1",
    category: "daily_life",
  },
  {
    id: "daily-008",
    de: "Er schläft immer sehr tief.",
    en: "He always sleeps very deeply.",
    level: "A2",
    category: "daily_life",
  },
  {
    id: "daily-009",
    de: "Wir gehen heute Abend ins Kino.",
    en: "We are going to the cinema tonight.",
    level: "A2",
    category: "daily_life",
  },
  {
    id: "daily-010",
    de: "Ich habe meine Schlüssel vergessen.",
    en: "I forgot my keys.",
    level: "B1",
    category: "daily_life",
  },

  // ── WORK & CAREER (10) ──
  {
    id: "work-001",
    de: "Sie bewirbt sich um eine neue Stelle.",
    en: "She is applying for a new position.",
    level: "B1",
    category: "career",
  },
  {
    id: "work-002",
    de: "Das Meeting beginnt um neun Uhr.",
    en: "The meeting starts at nine o'clock.",
    level: "A2",
    category: "career",
  },
  {
    id: "work-003",
    de: "Er arbeitet seit drei Jahren hier.",
    en: "He has worked here for three years.",
    level: "B1",
    category: "career",
  },
  {
    id: "work-004",
    de: "Wir müssen die Frist einhalten.",
    en: "We must meet the deadline.",
    level: "B2",
    category: "career",
  },
  {
    id: "work-005",
    de: "Das Projekt wurde pünktlich abgeschlossen.",
    en: "The project was completed on time.",
    level: "B1",
    category: "career",
  },
  {
    id: "work-006",
    de: "Sie hält heute eine Präsentation.",
    en: "She is giving a presentation today.",
    level: "B1",
    category: "career",
  },
  {
    id: "work-007",
    de: "Ich schreibe gerade einen Bericht.",
    en: "I am currently writing a report.",
    level: "B1",
    category: "career",
  },
  {
    id: "work-008",
    de: "Der Chef ist heute nicht im Büro.",
    en: "The boss is not in the office today.",
    level: "A2",
    category: "career",
  },
  {
    id: "work-009",
    de: "Wir haben eine wichtige Besprechung.",
    en: "We have an important meeting.",
    level: "B1",
    category: "career",
  },
  {
    id: "work-010",
    de: "Sie arbeitet sehr selbstständig.",
    en: "She works very independently.",
    level: "B2",
    category: "career",
  },

  // ── EMOTIONS & FEELINGS (10) ──
  {
    id: "emotions-001",
    de: "Er fühlt Heimweh nach seiner Familie.",
    en: "He feels homesick for his family.",
    level: "B1",
    category: "emotions",
  },
  {
    id: "emotions-002",
    de: "Sie ist sehr stolz auf ihre Arbeit.",
    en: "She is very proud of her work.",
    level: "B1",
    category: "emotions",
  },
  {
    id: "emotions-003",
    de: "Ich freue mich auf das Wochenende.",
    en: "I am looking forward to the weekend.",
    level: "A2",
    category: "emotions",
  },
  {
    id: "emotions-004",
    de: "Er ist heute sehr müde.",
    en: "He is very tired today.",
    level: "A1",
    category: "emotions",
  },
  {
    id: "emotions-005",
    de: "Sie zeigt große Beharrlichkeit beim Lernen.",
    en: "She shows great persistence in learning.",
    level: "B2",
    category: "emotions",
  },
  {
    id: "emotions-006",
    de: "Die Entscheidung war nicht einfach.",
    en: "The decision was not easy.",
    level: "B1",
    category: "emotions",
  },
  {
    id: "emotions-007",
    de: "Ich bin sehr dankbar für deine Hilfe.",
    en: "I am very grateful for your help.",
    level: "B1",
    category: "emotions",
  },
  {
    id: "emotions-008",
    de: "Er ärgert sich über die Verspätung.",
    en: "He is annoyed about the delay.",
    level: "B1",
    category: "emotions",
  },
  {
    id: "emotions-009",
    de: "Sie lacht immer sehr herzlich.",
    en: "She always laughs very warmly.",
    level: "A2",
    category: "emotions",
  },
  {
    id: "emotions-010",
    de: "Wir sind alle sehr aufgeregt.",
    en: "We are all very excited.",
    level: "A2",
    category: "emotions",
  },
];
