import type { CaseVerb } from "./types";

export const CASE_VERBS: CaseVerb[] = [
  {
    id: "sehen",
    infinitive: "sehen",
    conj3sg: "sieht",
    en: "to see",
    enPattern: "The {nom} sees the {akk}.",
    frame: ["nom", "akk"],
    rule: "Transitive verb — the object is Akkusativ (the target).",
    level: "B1",
  },
  {
    id: "kaufen",
    infinitive: "kaufen",
    conj3sg: "kauft",
    en: "to buy",
    enPattern: "The {nom} buys the {akk}.",
    frame: ["nom", "akk"],
    rule: "Transitive verb — direct object takes Akkusativ.",
    level: "B1",
  },
  {
    id: "lesen",
    infinitive: "lesen",
    conj3sg: "liest",
    en: "to read",
    enPattern: "The {nom} reads the {akk}.",
    frame: ["nom", "akk"],
    rule: "Transitive verb — what you read is Akkusativ.",
    level: "B1",
  },
  {
    id: "helfen",
    infinitive: "helfen",
    conj3sg: "hilft",
    en: "to help",
    enPattern: "The {nom} helps the {dat}.",
    frame: ["nom", "dat"],
    rule: "Dative verb — the person helped is Dativ (wem?), not Akkusativ.",
    level: "B1",
  },
  {
    id: "danken",
    infinitive: "danken",
    conj3sg: "dankt",
    en: "to thank",
    enPattern: "The {nom} thanks the {dat}.",
    frame: ["nom", "dat"],
    rule: "Dative verb — you thank someone (wem dankst du?).",
    level: "B1",
  },
  {
    id: "gehoeren",
    infinitive: "gehören",
    conj3sg: "gehört",
    en: "to belong to",
    enPattern: "The {akk} belongs to the {dat}.",
    frame: ["nom", "dat"],
    rule: "Dative verb — gehören always takes Dativ for the owner.",
    level: "B1",
  },
  {
    id: "folgen",
    infinitive: "folgen",
    conj3sg: "folgt",
    en: "to follow",
    enPattern: "The {nom} follows the {dat}.",
    frame: ["nom", "dat"],
    rule: "Dative verb — you follow someone (wem folgst du?).",
    level: "B1",
  },
  {
    id: "gefallen",
    infinitive: "gefallen",
    conj3sg: "gefällt",
    en: "to please / to like",
    enPattern: "The {akk} pleases the {dat}.",
    frame: ["nom", "dat"],
    rule: "Dative verb — the liker is Dativ: mir gefällt das Buch.",
    level: "B1",
  },
  {
    id: "geben",
    infinitive: "geben",
    conj3sg: "gibt",
    en: "to give",
    enPattern: "The {nom} gives the {dat} the {akk}.",
    frame: ["nom", "dat", "akk"],
    rule: "Ditransitive — receiver = Dativ, thing given = Akkusativ.",
    level: "B1",
  },
  {
    id: "zeigen",
    infinitive: "zeigen",
    conj3sg: "zeigt",
    en: "to show",
    enPattern: "The {nom} shows the {dat} the {akk}.",
    frame: ["nom", "dat", "akk"],
    rule: "Ditransitive — person shown to = Dativ, thing shown = Akkusativ.",
    level: "B1",
  },
  {
    id: "schenken",
    infinitive: "schenken",
    conj3sg: "schenkt",
    en: "to give (as gift)",
    enPattern: "The {nom} gives the {dat} the {akk}.",
    frame: ["nom", "dat", "akk"],
    rule: "Ditransitive — same pattern as geben.",
    level: "B1",
  },
  {
    id: "warten",
    infinitive: "warten",
    conj3sg: "wartet",
    en: "to wait",
    enPattern: "The {nom} waits for the {akk}.",
    frame: ["nom", "akk"],
    prep: { word: "auf", case: "akk" },
    rule: "Fixed preposition: warten auf + Akkusativ.",
    level: "B2",
  },
  {
    id: "denken",
    infinitive: "denken",
    conj3sg: "denkt",
    en: "to think",
    enPattern: "The {nom} thinks about the {akk}.",
    frame: ["nom", "akk"],
    prep: { word: "an", case: "akk" },
    rule: "Fixed preposition: denken an + Akkusativ.",
    level: "B2",
  },
  {
    id: "teilnehmen",
    infinitive: "teilnehmen",
    conj3sg: "nimmt teil",
    en: "to participate",
    enPattern: "The {nom} takes part in the {dat}.",
    frame: ["nom", "dat"],
    prep: { word: "an", case: "dat" },
    rule: "Fixed preposition: teilnehmen an + Dativ.",
    level: "B2",
  },
  {
    id: "interessieren",
    infinitive: "sich interessieren",
    conj3sg: "interessiert sich",
    en: "to be interested",
    enPattern: "The {nom} is interested in the {akk}.",
    frame: ["nom", "akk"],
    prep: { word: "für", case: "akk" },
    rule: "Reflexive + für: sich interessieren für + Akkusativ.",
    level: "B2",
  },
];

export function verbsForLevel(selected: CaseVerb["level"]): CaseVerb[] {
  const order = ["B1", "B2", "C1", "C2"];
  return CASE_VERBS.filter(v => order.indexOf(v.level) <= order.indexOf(selected));
}
