import type { PracticeQuestion, QuizQuestion } from "./types";

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "q-nom-m-def",
    sentence: "___ Mann liest ein Buch.",
    blank: "Der",
    hint: "Mann = masculine → Nominativ (subject)",
    options: ["Der", "Den", "Dem", "Des"],
    explanation: "Nominativ (subject) + masculine = der. Der Mann liest.",
    case: "nom",
    gender: "m",
    type: "def",
  },
  {
    id: "q-akk-m-def",
    sentence: "Ich sehe ___ Mann.",
    blank: "den",
    hint: "Mann = masculine → Akkusativ (direct object)",
    options: ["der", "den", "dem", "des"],
    explanation: "Akkusativ + masculine = den. der → den! (the big change)",
    case: "akk",
    gender: "m",
    type: "def",
  },
  {
    id: "q-dat-f-def",
    sentence: "Ich helfe ___ Frau.",
    blank: "der",
    hint: "Frau = feminine → Dativ (helfen takes Dativ)",
    options: ["die", "den", "der", "dem"],
    explanation: "Dativ + feminine = der. die → der! (feminine changes in Dative!)",
    case: "dat",
    gender: "f",
    type: "def",
  },
  {
    id: "q-gen-m-def",
    sentence: "Das ist das Haus ___ Mannes.",
    blank: "des",
    hint: "Mannes = masculine → Genitiv (possession)",
    options: ["der", "die", "des", "dem"],
    explanation: "Genitiv + masculine = des. der → des! Shows possession.",
    case: "gen",
    gender: "m",
    type: "def",
  },
  {
    id: "q-nom-n-def",
    sentence: "___ Kind spielt im Garten.",
    blank: "Das",
    hint: "Kind = neuter → Nominativ",
    options: ["Der", "Die", "Das", "Den"],
    explanation: "Nominativ + neuter = das. Das Kind.",
    case: "nom",
    gender: "n",
    type: "def",
  },
  {
    id: "q-akk-n-def",
    sentence: "Ich kaufe ___ Buch.",
    blank: "das",
    hint: "Buch = neuter → Akkusativ",
    options: ["das", "dem", "der", "des"],
    explanation: "Akkusativ + neuter = das. (neuter does NOT change in Akkusativ!)",
    case: "akk",
    gender: "n",
    type: "def",
  },
  {
    id: "q-dat-n-def",
    sentence: "Er gibt ___ Kind einen Ball.",
    blank: "dem",
    hint: "Kind = neuter → Dativ (indirect object)",
    options: ["das", "den", "dem", "des"],
    explanation: "Dativ + neuter = dem. das → dem! (geben takes Dativ for recipient)",
    case: "dat",
    gender: "n",
    type: "def",
  },
  {
    id: "q-nom-m-def-2",
    sentence: "___ Hund läuft schnell.",
    blank: "Der",
    hint: "Hund = masculine → Nominativ",
    options: ["Der", "Den", "Dem", "Die"],
    explanation: "Nominativ + masculine = der.",
    case: "nom",
    gender: "m",
    type: "def",
  },
  {
    id: "q-akk-f-def",
    sentence: "Ich sehe ___ Frau.",
    blank: "die",
    hint: "Frau = feminine → Akkusativ",
    options: ["die", "der", "den", "dem"],
    explanation: "Akkusativ + feminine = die. (feminine stays die in Akkusativ!)",
    case: "akk",
    gender: "f",
    type: "def",
  },
  {
    id: "q-dat-f-indef",
    sentence: "Ich wohne mit ___ Freundin.",
    blank: "einer",
    hint: "Freundin = feminine → Dativ (mit = always Dativ)",
    options: ["eine", "einer", "einem", "eines"],
    explanation: "mit + Dativ + feminine indefinite = einer. eine → einer!",
    case: "dat",
    gender: "f",
    type: "indef",
  },
  {
    id: "q-akk-m-indef",
    sentence: "Ich sehe ___ Mann.",
    blank: "einen",
    hint: "Mann = masculine → Akkusativ, indefinite article",
    options: ["ein", "einen", "einem", "eines"],
    explanation: "Akkusativ + masculine indefinite = einen. ein → einen! (the big change)",
    case: "akk",
    gender: "m",
    type: "indef",
  },
  {
    id: "q-nom-f-indef",
    sentence: "Das ist ___ gute Idee.",
    blank: "eine",
    hint: "Idee = feminine → Nominativ, indefinite",
    options: ["ein", "eine", "einer", "eines"],
    explanation: "Nominativ + feminine indefinite = eine.",
    case: "nom",
    gender: "f",
    type: "indef",
  },
  {
    id: "q-nom-m-indef",
    sentence: "___ Hund bellt laut.",
    blank: "Ein",
    hint: "Hund = masculine → Nominativ, indefinite",
    options: ["Ein", "Eine", "Einem", "Einen"],
    explanation: "Nominativ + masculine indefinite = ein.",
    case: "nom",
    gender: "m",
    type: "indef",
  },
  {
    id: "q-dat-n-indef",
    sentence: "Ich fahre mit ___ Auto.",
    blank: "einem",
    hint: "Auto = neuter → Dativ (mit = always Dativ)",
    options: ["ein", "eine", "einem", "eines"],
    explanation: "mit + Dativ + neuter indefinite = einem. ein → einem!",
    case: "dat",
    gender: "n",
    type: "indef",
  },
  {
    id: "q-nom-n-indef",
    sentence: "Das ist ___ Problem.",
    blank: "ein",
    hint: "Problem = neuter → Nominativ, indefinite",
    options: ["ein", "eine", "einer", "einem"],
    explanation: "Nominativ + neuter indefinite = ein.",
    case: "nom",
    gender: "n",
    type: "indef",
  },
];

export const PRACTICE_QUESTIONS: PracticeQuestion[] = [
  {
    id: "p-nom-m-def",
    sentence: "___ Hund beißt den Mann.",
    answer: "Der",
    options: ["Der", "Den", "Dem", "Die"],
    hint: "Hund = masculine, subject (Nominativ)",
    explanation: "Nominativ + masculine definite = Der",
    case: "nom",
    gender: "m",
  },
  {
    id: "p-akk-f-def",
    sentence: "Ich sehe ___ Frau.",
    answer: "die",
    options: ["die", "der", "dem", "den"],
    hint: "Frau = feminine, direct object (Akkusativ)",
    explanation: "Akkusativ + feminine = die (stays the same!)",
    case: "akk",
    gender: "f",
  },
  {
    id: "p-dat-m-def",
    sentence: "Er hilft ___ Mann.",
    answer: "dem",
    options: ["dem", "der", "den", "des"],
    hint: "Mann = masculine, indirect object (Dativ) — helfen takes Dativ!",
    explanation: "Dativ + masculine = dem (der→dem)",
    case: "dat",
    gender: "m",
  },
  {
    id: "p-gen-f-def",
    sentence: "Das Auto ___ Frau ist rot.",
    answer: "der",
    options: ["der", "die", "dem", "des"],
    hint: "Frau = feminine, possession (Genitiv)",
    explanation: "Genitiv + feminine = der (die→der)",
    case: "gen",
    gender: "f",
  },
  {
    id: "p-nom-n-def",
    sentence: "___ Kind isst einen Apfel.",
    answer: "Das",
    options: ["Das", "Der", "Die", "Den"],
    hint: "Kind = neuter, subject (Nominativ)",
    explanation: "Nominativ + neuter = Das",
    case: "nom",
    gender: "n",
  },
  {
    id: "p-akk-n-def",
    sentence: "Ich kaufe ___ Auto.",
    answer: "das",
    options: ["das", "dem", "der", "den"],
    hint: "Auto = neuter, direct object (Akkusativ)",
    explanation: "Akkusativ + neuter = das (no change!)",
    case: "akk",
    gender: "n",
  },
  {
    id: "p-dat-m-def-2",
    sentence: "Er fährt mit ___ Bus.",
    answer: "dem",
    options: ["dem", "den", "der", "die"],
    hint: "Bus = masculine, Dativ after \"mit\"",
    explanation: "mit + Dativ + masculine = dem",
    case: "dat",
    gender: "m",
  },
  {
    id: "p-dat-f-def",
    sentence: "Ich wohne mit ___ Mutter.",
    answer: "der",
    options: ["der", "die", "dem", "den"],
    hint: "Mutter = feminine, Dativ after \"mit\"",
    explanation: "Dativ + feminine definite = der (die→der!)",
    case: "dat",
    gender: "f",
  },
  {
    id: "p-nom-m-def-2",
    sentence: "___ Mann gibt dem Kind das Buch.",
    answer: "Der",
    options: ["Der", "Den", "Die", "Dem"],
    hint: "Mann = subject (Nominativ masculine)",
    explanation: "Nominativ + masculine = Der",
    case: "nom",
    gender: "m",
  },
  {
    id: "p-dat-m-def-3",
    sentence: "Ich helfe ___ Freund.",
    answer: "dem",
    options: ["dem", "den", "der", "die"],
    hint: "Freund = masculine, indirect object (Dativ)",
    explanation: "Dativ + masculine = dem",
    case: "dat",
    gender: "m",
  },
  {
    id: "p-akk-n-indef",
    sentence: "Ich kaufe ___ Buch für meine Freundin.",
    answer: "ein",
    options: ["ein", "eine", "einen", "einem"],
    hint: "Buch = neuter, Akkusativ, indefinite article",
    explanation: "Akkusativ + neuter indefinite = ein (no change for neuter!)",
    case: "akk",
    gender: "n",
  },
  {
    id: "p-nom-f-indef",
    sentence: "Das ist ___ gute Idee!",
    answer: "eine",
    options: ["eine", "ein", "einen", "einer"],
    hint: "Idee = feminine, Nominativ, indefinite",
    explanation: "Nominativ + feminine indefinite = eine",
    case: "nom",
    gender: "f",
  },
  {
    id: "p-akk-m-def",
    sentence: "Ich sehe ___ Mann.",
    answer: "den",
    options: ["den", "der", "dem", "des"],
    hint: "Mann = masculine, direct object (Akkusativ)",
    explanation: "Akkusativ + masculine = den (der→den!)",
    case: "akk",
    gender: "m",
  },
];

export function shuffleQuestions<T>(items: T[]): T[] {
  const copy = items.slice();
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    const tmp = copy[i];
    copy[i] = copy[j];
    copy[j] = tmp;
  }
  return copy;
}
